PROJECT = demo_cowboy
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0



DEPS = cowboy jsx recon reloader
dep_cowboy_commit = 2.5.0
dep_jsx = git https://github.com/talentdeficit/jsx 2.9.0
dep_recon = git https://github.com/ferd/recon.git 2.4.0
dep_reloader = git https://github.com/newforks/reloader.git master

DEP_PLUGINS = cowboy
ERLC_OPTS = -W0


include erlang.mk